### ISSUE TITLE
Should it be newTab or newWindow?

### ISSUE THREAD

**Issue by kud** [kud/browser-js#2]
```javascript
newTab: function( url ) {
  window.open(url,'_blank')
}
```
opens normally a new window but lots of browsers handle it as a new tab by default, should it be called `newTab` or `newWindow`?

**Comment by MoOx** [comment]
openUrl

**Comment by kud** [comment]
`openUrl` seems indeed generic but what the difference with `visit`? Could be unclear.

**Comment by nfroidure** [comment]
`Browser.fork`

**Comment by kud** [comment]
`fork`? weird term but why not.

**Comment by nfroidure** [comment]
Or, `Browser.spawn`

**Comment by kud** [comment]
Ca doit parler quand tu fais du node ou quand tu es anglais mais comme ça, ça me parait bizarre. Peut-être que `openUrl` est le mieux.

**Comment by nfroidure** [comment]
Disons que ça traduit le fait qu'un nouveaux processus est lancé. Ce sont les termes employé dans les libs standard pour la création de processus.

**Comment by bloodyowl** [comment]
`Browser.openInNewContext`

**Comment by kud** [comment]
`openNewContext`?

**Comment by bloodyowl** [comment]
I think that `openNewContext` makes it unclear the method takes a `url` parameter

**Comment by kud** [comment]
`newContext` ? O:)

As it's only for a browser, we understand we speak about a webpage or tab or window.

**Comment by bloodyowl** [comment]
that's not the issue IMO, the method name should describe what it does and be intuitive.

if I see a `openNewContext` or a `newContext` I expect the method to open a new context & to return the child `window` object so I can manipulate it afterwards.

**Comment by kud** [comment]
I think newWindow should be the correct name as it really opens a new window BUT some (most of) browsers now translate that as a new tab.

Or I do an alias and we've got newTab and newWindow.

**Comment by kud** [comment]
Fixed by making newTab as alias of newWindow
