### ISSUE TITLE
Demo URL not working /o\

### ISSUE THREAD

**Issue by LukyVj** [kud/browser-js#6]

**Comment by kud** [comment]
There's no demo :p

**Comment by LukyVj** [comment]
There were a link, right here, like 5minutes ago :p 
![](http://puu.sh/pY2bh/d817c20313.png)

**Comment by kud** [comment]
Ha yes but it wasn't a demo, it was just a link to a better README. But this service doesn't work anymore so I've removed the link, yes. Thank you anyway. ;)
